# -*- coding: utf-8 after-save-hook: (lambda nil (org-html-export-to-html)) org-refile-targets: (("startup.org" :maxlevel . 1024)) -*-
#+INFOJS_OPT: path:~/lib/org-info.js view:overview toc:nil ltoc:nil


* mf

** exemplo de informativo da ativa

                                  ATIVA Investimentos
  
                            Call matinal do dia 16/11/2017

  
                                 Comunicado Importante

                                Olá Denilson, bom dia.

  

 Neste feriado de quarta feira, em Brasília, o Planalto anunciou o cronograma
 esperado para a privatização da Eletrobras, que deverá tramitar no legislativo
 até março, com a posterior venda no início do segundo semestre. O governo
 espera arrecadar 12 bilhões de reais com a venda, que deve integrar mais uma
 estrutura de itens não-recorrentes com efeito positivo no orçamento, tendo em
 vista o fechamento das contas de 2018. A empresa deverá desembolsar ainda, mais
 30 bilhões de reais a título de bônus de assinatura das usinas que serão
 descotizadas. Este segundo pagamento, no entanto, será feito em parcelas, com
 cronograma ainda não divulgado.
  
 Ainda na política, Temer segue investindo na aprovação da reforma da
 previdência, supostamente colocando a reforma ministerial como prêmio junto aos
 partidos para arrecadar o apoio necessário. Ainda no radar, temos a entrada da
 reforma trabalhista em vigor, que deverá levantar contestação por parte dos
 sindicatos devido à perda de receita que deverá decorrer do fim da
 obrigatoriedade na contribuição sindical.
  
 Lá fora o mercado deverá focar na votação da reforma tributária do Trump na
 Câmara. Depois de levantar uma alta rejeição por parte dos agentes, a proposta
 foi renegociada e diluída, com aval do partido Republicano, e agora segue para
 votação no Legislativo. Nos Estados Unidos teremos ainda os pedidos de auxílio
 desemprego divulgados às 11h30; logo depois, às 12h15, o Fed divulga a produção
 industrial americana de outubro. Neste momento temos mercados na Europa e
 Estados Unidos operando em alta. No mercado de petróleo temos mais um pregão de
 recuo, com o Brent já cotando na casa dos 61 dólares o barril. 
  

 [tcW126ABF0][QK6K4fABF0][yqIBa5ABF0][QGML1cABF0]
  

  
 ATIVA Investimentos

 PODCAST

 Ouça o aúdio do nosso podcast e acompanhe o nosso call pelo seu smartphone
 atráves do iTunes e do SoundCloud sem nenhum custo. Vale lembrar que o acesso
 pode ser feito através do IOS, Android e Windons Phone. Siga a nossa equipe de
 analistas e receba as principais informações do mercado politico e economico. 

  
 [1MTZ71ABF0] [D7aS30ABF0]



 ATIVA Investimentos

 AGENDA

 07h30    Reino Unido/ONS: Vendas no varejo - Outubro
 08h00    FGV: IGP-10 - Novembro
 08h00    FGV: Índice de Preços ao Consumidor (IPC) - 2ª quadrissemana de
 novembro
 08h00    Zona do euro/Eurostat: índice de preços ao consumidor (CPI) - Outubro
 10h00    Ministério da Fazenda: boletim Prisma Fiscal - Novembro
 11h30    EUA/Deptº do Trabalho: Índice de preços das importações - Outubro
 11h30    EUA/Fed de Filadélfia: índice de atividade regional - Novembro
 11h30    EUA/Deptº do Trabalho: pedidos de auxílio-desemprego - Semana até 11/
 11
 12h15    EUA/Fed: Produção industrial - Outubro
 12h30    Banco Central divulga o fluxo cambial semanal
 -              EUA: presidente Donald Trump reúne-se com deputados do partido
 Republicano antes da votação da reforma tributária
 -              EUA: plenário da Câmara dos Representantes deve votar proposta
 de reforma tributária

  
  

 ATIVA Investimentos

 DESTAQUES CORPORATIVOS

   • Governo espera que Senado aprove a privatização da Eletrobrás até março:
     Estado
   • Petrobras: Cia. é notificada de arbitragem por fundos de pensão
       □ Parente: Não assino acordo cessão onerosa se cia. tiver que pagar
       □ Parente: Meta é assinar venda de US$ 21 bi em ativos até jun./18
       □ Parente: Cia. não está aberta a tratar corte de produção com Opep
       □ Produção de petróleo e gás outubro foi 2,77 mi boed
   • Copel diz que não entregará balanço no prazo
   • Cemig: Receita 3T supera maior est.
   • Sabesp: Lucro líquido 3T supera maior est.
   • Metal Leve: Receita 3T em linha est.
   • Direcional: Prejuízo líquido 3T maior que est.
   • Licença da Samarco pode ser votada em Minas Gerais neste mês
   • Cielo tem rating elevado pela Fitch p/BBB-; perspectiva negativa
   • BR Malls: Lucro ajustado 3T supera maior est.
   • Light Energia aprova emissão de R$ 100 mi em debêntures
   • Eneva é reiniciada com recomendação de compra pelo Goldman, preço-alvo R$
     17
   • CCR entra na disputa pela Invepar: Globo


  
 ATIVA Investimentos

 ÍNDICE, JUROS, MOEDAS E COMMODITIES

           Ásia               Tóquio        1,47%        H. Kong          0,58%         Xangai       -0,10%

          Europa             Londres        0,01%         Paris           0,59%       Frankfurt      0,60%

          Futuros              Dow          0,00%          S&P            0,32%         Nasdaq       0,40%

         Petroleo              WTI          55,22         -0,20%          Brent         61,72        -0,24%

        Min. Ferro            Fe 62%        61,84         -2,11%                                        

           Moeda             USD/BRL        3,32          -1,08%         EUR/USD         1,18        -0,16%


 *Cotações retiradas em 16/11/2017 08:08

 ATIVA Investimentos



 TAXA DE JUROS - DÍVIDA NACIONAL VENCIMENTO 10 ANOS

         10Y Bonds            Yield       ∆ Diária      ∆ Semanal       ∆ Mensal

            EUA               2,37%        -0,31%         -0,20%         -0,60%

        Inglaterra            1,31%        -0,18%         -0,40%          0,08%

          Brasil              10,49%        0,04%         -2,13%         -2,67%

          Espanha             1,55%        -0,04%         -0,21%          0,16%

         Alemanha             0,39%        -0,17%         -0,18%         -0,22%

          Itália              1,84%        -0,08%         -0,25%          1,65%

          Grécia              5,10%        -0,33%         0,03%           2,84%

          França              0,74%        -0,14%         0,03%           0,41%

           China              3,93%         0,57%         -0,24%         -1,81%

           Japão              0,05%        -0,06%         -0,22%          0,16%

  

 *Cotações retiradas em 16/11/2017 08:08

 ATIVA Investimentos

 PESSOA FÍSICA


 Compra:          BBDC4; VALE3; 
 Venda:           BBAS3; FIBR3; 
 Compra/Venda:    PETR4; PETR3; RAIL3; GOAU4; USIM5; CSNA3; GGBR4; MGLU3; 

 * Ações mais negociadas pelos clientes da ATIVA

 ATIVA Investimentos

 INSTITUCIONAL


 Compra:            BRKM5; CPLE6; PETR4; BRAP4; BBDC4; WEGE3; LAME4; 
 Venda:             VALE3; CCRO3; BVMF3; MULT3; LIGT3; SUZB3; ESTC3; 
 Compra/Venda:      BOVA11; BBDC3; USIM5; 

 * Ações mais negociadas pelos clientes da ATIVA

 ATIVA Investimentos

  

 Phillip Soares, CFA
 Lucas Claro, CNPI
 Lucas Marins, CNPI
 21 3515 0200
 ATIVA Investimentos

  
                                 ATIVA Investimentos
                                 ATIVA Investimentos
                     Capitais e Regiões Metropolitanas 4007 2447
                            Demais Regiões 0800 285 0147
                               Ouvidoria 0800 282 9900
                     Email atendimento@ativainvestimentos.com.br
  
     ATIVA         ATIVA         ATIVA         ATIVA         ATIVA         ATIVA
 Investimentos Investimentos Investimentos Investimentos Investimentos Investimentos
  
 As informações contidas neste material são de caráter meramente informativo e
 não constituem promessa de rentabilidade, bem como não se trata de qualquer
 tipo de aconselhamento para a realização de investimento, não devendo ser
 utilizadas com este propósito, nem entendidas como tal.
 Os dados aqui apresentados foram obtidos ou baseados em fontes públicas e
 consideradas confiáveis,  A Ativa Investimentos não garante que tais dados
 sejam precisos ou completos, nem poderá ser responsabilizada por quaisquer
 perdas diretas advindas do aqui contido.
 Desempenho passado não representa garantia de resultados futuros e resultados
 futuros podem não cumprir com as expectativas devido a diversos fatores.
 Antes de tomar a decisão de aplicar em qualquer operação, os potenciais
 investidores devem considerar cuidadosamente sua própria situação financeira,
 seus objetivos de investimento, todas as informações disponíveis e, em
 particular, avaliar os fatores de risco aos quais o investimento está sujeito.
 As decisões de investimento são de responsabilidade total e irrestrita do
 Investidor. A Ativa Investimentos não pode ser responsabilizada por prejuízos
 oriundos de decisões tomadas com base nas informações aqui apresentadas.
 Para informações sobre os produtos e serviços oferecidos pela Ativa,
 acessewww.ativainvestimentos.com.br ou www.comoinvestir.com.br, ou entre em
 contato com o seu assessor ou com a nossa Central de Atendimento: 0800 285
 0147.
 Ouvidoria: 0800 282 9900
               Descadastre-se caso não queira receber mais e-mails


* AI & ML

** http://blog.algorithmia.com/2016/04/accelerating-artificial-intelligence-development/

** http://www.nytimes.stfi.re/2016/04/07/science/artificial-intelligence-when-is-the-singularity.html?_r=2&sf=dnvaze#aa

** http://www.shivonzilis.stfi.re/machineintelligence?sf=jngojv#aa

** [[https://www.coursera.org/learn/machine-learning][Machine Learning course on Coursera]]

** http://playground.tensorflow.org/

** http://a16z.com/2016/06/10/ai-deep-learning-machines/

** http://deepjazz.io/

** http://deeplearning.net/tutorial/lstm.html

** [[https://www.oreilly.com/ideas/the-current-state-of-machine-intelligence-3-0?utm_content=buffer964e5&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer][The current state of machine intelligence 3.0 - O'Reilly Media]]



* misc

** http://itera.com.br/Analises/

** http://www.semantix.com.br/


* blockchain

** https://windowsontheory.org/2017/06/15/bitcoin-and-theoretical-computer-science-guest-post-by-eli-ben-sasson/
** expolondrina
   
   uma das startups que se deram bem (apoio IBM e váo receber aporte da
   SPVentures) usou o blockchain da IBM como livro registro para contrato de
   transações de compra e venda de insumos x grãos http://bart.digital/


** [[http://avc.com/2017/04/video-of-the-week-the-mit-bitcoin-experiment/?utm_source%3Dfeedburner&utm_medium%3Dfeed&utm_campaign%3DFeed%253A%2BAVc%2B%2528A%2BVC%2529][The MIT Bitcoin Experiment]]
** https://youtu.be/90rmBzT8-J0

** http://marmelab.com/blog/2016/04/28/blockchain-for-web-developers-the-theory.html

** https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/492972/gs-16-1-distributed-ledger-technology.pdf

** https://bitcoinmagazine.com/articles/what-are-the-use-cases-for-private-blockchains-the-experts-weigh-in-1466440884

** http://www.multichain.com/

** https://chain.com/press-releases/visa-introduces-international-b2b-payment-solution-built-on-chains-blockchain-technology/

** https://chain.com/docs/core/get-started/five-minute-guide

** http://bitfury.com/

** http://www.cobaltdl.com/

** https://www.bitcoin.com/

** http://bitcoincharts.com/bitcoin/

** https://angel.co/blockchains

** https://medium.com/the-intrepid-review/the-top-10-blockchain-startups-to-watch-in-2016-the-leaders-who-are-changing-the-game-6195606b0d70#.r30ufkjm9

** http://venturebeat.com/2017/01/28/cisco-bosch-and-foxconn-are-building-blockchain-tech-for-the-internet-of-things/

** https://techcrunch.com/2017/03/19/ibm-unveils-blockchain-
as-a-service-based-on-open-source-hyperledger-fabric-technology/

IBM <https://www.ibm.com/> unveiled its “Blockchain as a Service” today,
which is based on the open source Hyperledger Fabric
<https://www.hyperledger.org/>, version 1.0 from The Linux Foundation.

https://www.hyperledger.org/



* voronoi

Vi todos os links, procurei por outros, tem algumas coisas no Brasil também, Unicamp, UFSC, mesmo escopo.

Pelo menos para mim ficou muito claro do que se trata. :)

Não achei nada com cara comercial, o que é ótimo.

Começo a imaginar que só entregar o mapeamento em várias situações de jogo é bom mas insuficiente, talvez como parte do serviço precisaremos entregar o '"book" também uma análise, talvez um diagnóstico, joves e mais analíticos treinadores ou estudiosos de futebol talvez pudessem fazer isso.

A outra parte é um bom esquema de fotografar as posições nos momentos, mas acho que uma boa câmara bem instalada resolve isso (pelo menos para o campo de treino ou os jogos mandados em casa).

Acho, não tenho certeza, que os jogadores não poderiam (limitação Fifa) jogar com algum tipo de sensor em seus corpos.

Trinta times no mundo pagam 20 mil dólares por um serviço bem empacotado? Sim, acho que sim.

Parece que vale dar um passo em frente.

** https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0ahUKEwiEzN2SoLDRAhWCjJAKHRVWCgcQFggrMAI&url=http%3A%2F%2Frevistas.um.es%2Fcpd%2Farticle%2FviewFile%2F223151%2F173381&usg=AFQjCNEZ08abFejuwcpuYAROIC1iCe8FaQ&sig2=nIQccuJdX_VtlqeRgcWwMg

** https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=11&cad=rja&uact=8&ved=0ahUKEwiEzN2SoLDRAhWCjJAKHRVWCgcQFghLMAo&url=http%3A%2F%2Fwww.lana.lt%2Fjournal%2F14%2FKim.pdf&usg=AFQjCNEGHs4711qjOqrQnti_dk0Am490oQ&sig2=cHOD6dXG6J46noQ17Rn6sA

** https://books.google.com.br/books?id=vxB6DQAAQBAJ&pg=PT137&lpg=PT137&dq=voronoi+diagram+sports&source=bl&ots=HxXdQg1-Co&sig=GOqLrMLAG3C6f5B9FivHd7YlAMA&hl=en&sa=X&ved=0ahUKEwiEzN2SoLDRAhWCjJAKHRVWCgcQ6AEIVDAL

** https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=13&cad=rja&uact=8&ved=0ahUKEwiEzN2SoLDRAhWCjJAKHRVWCgcQFghZMAw&url=http%3A%2F%2Frepositorio.ipl.pt%2Fbitstream%2F10400.21%2F5070%2F4%2FSpatial%2520dynamics%2520of%2520team%2520sports%2520exposed%2520by%2520Voronoi%2520diagrams.rep.pdf&usg=AFQjCNHZ8q-ILi_g6WX1rvDvcmdWbeuXjQ&sig2=UoaqVcVYijYX1-arKw2yKg

** https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=17&cad=rja&uact=8&ved=0ahUKEwiEzN2SoLDRAhWCjJAKHRVWCgcQFghvMBA&url=https%3A%2F%2Fwww.technologyreview.com%2Fs%2F600957%2Fbig-data-analysis-is-changing-the-nature-of-sports-science%2F&usg=AFQjCNFjGa_qE3Avo5hegVv0oTQ8-k0ZcA&sig2=WJfVIjkUTzflcKyHrFe9yw

** https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=18&cad=rja&uact=8&ved=0ahUKEwiEzN2SoLDRAhWCjJAKHRVWCgcQFgh1MBE&url=http%3A%2F%2Fwww.redalyc.org%2Farticulo.oa%3Fid%3D227038699012&usg=AFQjCNFAM5zld6piHSUF_ZjuGBvzuN8s1A&sig2=H0wuYBxi3s2uKtO7typFqg




** http://www.sciencedirect.com/science/article/pii/S0167945712000668
   
   Abstract
   
   Team sports represent complex systems: players interact continuously
   during a game, and exhibit intricate patterns of interaction, which can
   be identified and investigated at both individual and collective
   levels. We used Voronoi diagrams to identify and investigate the spatial
   dynamics of players’ behavior in Futsal. Using this tool, we examined 19
   plays of a sub-phase of a Futsal game played in a reduced area (20 m2)
   from which we extracted the trajectories of all players. Results
   obtained from a comparative analysis of player’s Voronoi area (dominant
   region) and nearest teammate distance revealed different patterns of
   interaction between attackers and defenders, both at the level of
   individual players and teams. We found that, compared to defenders,
   larger dominant regions were associated with attackers. Furthermore,
   these regions were more variable in size among players from the same
   team but, at the player level, the attackers’ dominant regions were more
   regular than those associated with each of the defenders. These findings
   support a formal description of the dynamic spatial interaction of the
   players, at least during the particular sub-phase of Futsal
   investigated. The adopted approach may be extended to other team
   behaviors where the actions taken at any instant in time by each of the
   involved agents are associated with the space they occupy at that
   particular time.


* incoming
** Linux Foundation-led Hyperledger launches Fabric: 

the group's first
production-ready ledger code; enables companies in numerous industries to build
blockchain-based business apps; The Hyperledger Project is an open-source
collaborative group with more than 120 members
** From: Denilson Farias <denilson.farias@gmail.com>
Subject: Re: Achei interessante
To: Renato Carmo <renato.carmo.rc@gmail.com>
Date: Tue, 4 Jul 2017 11:28:29 -0300 (1 day, 23 hours, 54 minutes ago)

sim, bem legal,

mas em geral um aspecto pouco é abordado no tema, o
custo computacional de gerar blocos válidos novos aceitos pela rede,

do que entendi há um enorme desperdício na geração de blocos que depois não
são aceitos (maioria),

e é ai que acredito que tem um espaço para duas pessoas geniais :) (ou pelo
menos uma) fuçarem uma oportunidade única :)

não consigo enxergar vários dos exemplos citados (música, arquivos) sendo
viáveis com uma plataforma que demora e custa tanto para gerar um bloco,

https://www.quora.com/How-much-CPU-time-is-needed-to-mine-1-bitcoin

https://blockchain.info/charts/difficulty?address=&daysAverageString=1&scale=0&showDataPoints=false&show_header=true&timespan=1year


If you look at how much processing power is competing for mining bitcoins,
it currently stands at 250 million gigahashes per second.

A typical CPU can perform 5 million hashes per second, so the overall
bitcoin hash rate is equivalent to 50 billion CPUs.

Also, the hash rate is growing exponentially (see Bitcoin Difficulty
<https://blockchain.info/charts/difficulty?address=&daysAverageString=1&scale=0&showDataPoints=false&show_header=true&timespan=1year>
).

On the other hand, most of this hashing is managed by a small number of
mining pools (see Hashrate Distribution <https://blockchain.info/pools>).
It would only require collusion of the top 2-3 pools to mount a 51% attack.

On Tue, Jul 4, 2017 at 8:47 AM, Renato Carmo <renato.carmo.rc@gmail.com>
wrote:

> https://www.linkedin.com/pulse/blockchain-explanation-
> your-mum-could-understand-jamie-skella
>
> --
> Renato
> renato.carmo.rc@gmail.com
> http://www.inf.ufpr.br/renato
>



-- 
Abraços,

Denilson
** https://www.linkedin.com/pulse/blockchain-explanation-your-mum-could-understand-jamie-skella
** http://www.visualcapitalist.com/chart-coin-universe-keeps-expanding/

-- 
Abraços,

Denilson
** Um compilado de links, desculpe a demora.


CURSOS

Programa de MSc online em Bitcoin
http://digitalcurrency.unic.ac.cy/free-introductory-mooc/
Obs. Primeira disciplina é gratuita, parece valer a pena, mas não tive
tempo de fazê-lo.

Curso com a mesma pegada do MSc, mas resumido numa disciplina
https://pt.coursera.org/learn/cryptocurrency

Upcoming...
http://blockchainu.co/


ETHEREUM (empresa)

https://pt.wikipedia.org/wiki/Ethereum
https://www.ethereum.org/
https://www.crunchbase.com/organization/ethereum#/entity


COMPLIANCE

Será que esses caras são relevantes?
https://www.smartchains.com.br/blank-2

Pra estruturar uma empresa mirando o mercado Bitcoin é bem importante estar
com o compliance em dia. Esses caras prestam consultoria se a empresa vai
lidar com Bitcoin.
https://www.bitaml.com/


NOTÍCIAS

Não sei qual é a maior/melhor referência, eis algumas que parecem boas.

https://blogs.wsj.com/riskandcompliance/tag/bitcoin/

http://www.the-blockchain.com/

http://www.coindesk.com/

-

Além disso, tenho um ex-colega que abriu uma empresa no ano retrasado em
smart contracts, sem usar blockchain, no ramo jurídico (mercado grande e
carente, Brasil já tem quase 1m advogados). Apesar de ele ter saído da
empresa, parece estar dando certo. Posso colocar-lhes em contato.

Conte comigo pra qualquer coisa.


Aquele abraço!
** psc,

---------- Forwarded message ----------
From: Denilson Farias <denilson.farias@gmail.com>
Date: 2017-05-03 11:06 GMT-03:00
Subject: Bitcoin a $ 1.470 doletas
To: Luiz Vieira <luizvieira@gmail.com>, Luciano Juvinski <juvinski@gmail.com
>


quando comecei a acompanhar estava $600

https://price.bitcoin.com/

-- 
Abraços,

Denilson



-- 
Abraços,

Denilson
** https://singularityhub.com/2017/01/31/the-struggle-to-make-ai-less-biased-than-its-creators/?utm_source=Singularity+Hub+Newsletter&utm_campaign=a3b8608ad2-Hub_Weekly_Newsletter&utm_medium=email&utm_term=0_f0cf60cdae-a3b8608ad2-58117473
** http://diversity.ai/

** blockchain (deni)

*** explicações

**** [[http://marmelab.com/blog/2016/04/28/blockchain-for-web-developers-the-theory.html][The Blockchain Explained to Web Developers, Part 1: The Theory]]

**** [[https://bitcoinmagazine.com/articles/what-are-the-use-cases-for-private-blockchains-the-experts-weigh-in-1466440884][What Are the Use Cases for Private Blockchains? The Experts Weigh In]]


*** software

**** [[http://www.multichain.com/][Multichain: open platform for blockchain applications]]

**** [[https://chain.com/docs/core/get-started/five-minute-guide][Chain Core: 5-Minute Guide]]


*** notícias

**** [[https://chain.com/press-releases/visa-introduces-international-b2b-payment-solution-built-on-chains-blockchain-technology/][Visa Introduces International B2B Payment Solution Built on Chain’s Blockchain Technology]]


*** empresas

**** [[http://bitfury.com/][The Bitfury Group: full service Blockchain technology company]]

**** [[http://www.cobaltdl.com/][Cobalt: reengineering financial markets]]

**** [[https://www.bitcoin.com/][bitcoin]]

***** [[http://bitcoincharts.com/bitcoin/][Bitcoin Network]]

**** startups

***** [[https://angel.co/blockchains][Blockchains Startups]]

***** [[https://medium.com/the-intrepid-review/the-top-10-blockchain-startups-to-watch-in-2016-the-leaders-who-are-changing-the-game-6195606b0d70#.r30ufkjm9][The Top 10 Blockchain Startups to Watch in 2016]]



